# Release the packages

name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.x"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      # Install stuff
      - name: Install Dependencies
        run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Do releases
      - name: semantic-release
        run: |
          npm config set workspaces-update false |
          pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
