name: Prettier Check
on: [pull_request]

jobs:
  prettier:
    if: "!contains(github.event.pull_request.title, 'WIP!')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.x"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install Dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm prettier --check .
